/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiPublicProductsRouteImport } from './routes/api/public/products'
import { Route as ApiPublicVideosRouteImport } from './routes/api/public/videos'
import { Route as ApiPublicOrdersOrderNumberRouteImport } from './routes/api/public/orders.$orderNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsRoute = ApiPublicProductsRouteImport.update({
  id: '/api/public/products',
  path: '/api/public/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideosRoute = ApiPublicVideosRouteImport.update({
  id: '/api/public/videos',
  path: '/api/public/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersOrderNumberRoute =
  ApiPublicOrdersOrderNumberRouteImport.update({
    id: '/api/public/orders/$orderNumber',
    path: '/api/public/orders/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/api/public/videos': typeof ApiPublicVideosRoute
  '/api/public/orders/$orderNumber': typeof ApiPublicOrdersOrderNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/api/public/videos': typeof ApiPublicVideosRoute
  '/api/public/orders/$orderNumber': typeof ApiPublicOrdersOrderNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/api/public/videos': typeof ApiPublicVideosRoute
  '/api/public/orders/$orderNumber': typeof ApiPublicOrdersOrderNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/public/products'
    | '/api/public/videos'
    | '/api/public/orders/$orderNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/public/products'
    | '/api/public/videos'
    | '/api/public/orders/$orderNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/public/products'
    | '/api/public/videos'
    | '/api/public/orders/$orderNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiPublicProductsRoute: typeof ApiPublicProductsRoute
  ApiPublicVideosRoute: typeof ApiPublicVideosRoute
  ApiPublicOrdersOrderNumberRoute: typeof ApiPublicOrdersOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products': {
      id: '/api/public/products'
      path: '/api/public/products'
      fullPath: '/api/public/products'
      preLoaderRoute: typeof ApiPublicProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/videos': {
      id: '/api/public/videos'
      path: '/api/public/videos'
      fullPath: '/api/public/videos'
      preLoaderRoute: typeof ApiPublicVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders/$orderNumber': {
      id: '/api/public/orders/$orderNumber'
      path: '/api/public/orders/$orderNumber'
      fullPath: '/api/public/orders/$orderNumber'
      preLoaderRoute: typeof ApiPublicOrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiPublicProductsRoute: ApiPublicProductsRoute,
  ApiPublicVideosRoute: ApiPublicVideosRoute,
  ApiPublicOrdersOrderNumberRoute: ApiPublicOrdersOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
